# This is the configuration file for the example website of the Hugo theme
# Astatine (see https://github.com/hugcis/hugo-astatine-theme).
#
# The URL from which the site will be served
baseurl = "https://xuruoyuroy.github.io/"
# Language used
languageCode = "en-us"
# Website title
title = "Ruoyu Xu"
# Theme used
theme = "hugo-astatine-theme"

preserveTaxonomyNames = true
rssLimit = 10
paginate = 10

# Code highlighting
pygmentsCodefences = true
pygmentsStyle = "native"

# Taxonomies (only tags and categories are supported out of the box but you can
# add more)
[taxonomies]
    category = "categories"  
    tag = "tags"

# Configure permalinks style
[permalinks]
    post = "/:slug/"
    page = "/:slug/"

# # Configure main navbar links. They can have a weight to select the order.
# # This links to content within the content/post/ folder

[[menu.main]]
    name = ""
    url = "https://github.com/XuRuoyuRoy"
    weight = -110

[[menu.main]]
    name = "Scholar"
    url = "https://scholar.google.com/citations?hl=en&user=M7Kwv6gAAAAJ"
    weight = -120

# [[menu.main]]
#     name = "Posts"
#     url = "/post/"
#     weight = -150

# This links to the page about.md
[[menu.main]]
    name = "Research"
    url = "/research/"
    weight = -130

[[menu.main]]
    name = "Resume"
    url = "/edu/"
    weight = -160

[[menu.main]]
    name = "Publications"
    url = "/pub/"
    weight = -150

# # Make the tags and categories pages accessible directly from the navbar.
# [[menu.main]]
#     name = "Tags"
#     url = "/tags/"
#     weight = -120

# [[menu.main]]
#     name = "Categories"
#     url = "/categories/"
#     weight = -130

# Site wide params and SEO
[params]
    # Site description. Individual pages can have descriptions too but if
    # missing it will fallback to that one.
    description = """The homepage of Roy. """
    # Author of the site
    authorName = "Ruoyu Xu"
    # Main image for the author. This will be the default image for SEO.
    [params.imgname]
        name = "img/ry.jpg"
        # Add an alt description for the image
        alt = "Profile picture"

    # Indicate if you host Katex yourself. Defaults to using the CDN KaTex.
    # hostedKaTex = false

    # Optional: add a twitter handle and mastodon handle for SEO.
    # [params.twitter]
        # name = "@Jack_harkness"
    # [params.mastodon]
        # name = "@jkharkness"
        # host = "mastodon.social"
    
    # Enable link to feed in footer
    blogrss = true

    # Enable pingback and webmention via webmention.io
    # webmention = "hugocisneros.com"


# Sitemap location (default is /sitemap.xml)
[sitemap]
  filename = "sitemap.xml"
